# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  NodeCount = 3

  (1..NodeCount).each do |i|

    config.vm.define "archvm#{i}" do |node|

      node.vm.box               = "generic/arch"
      node.vm.box_check_update  = false
      node.vm.hostname          = "archvm#{i}.example.com"

      node.vm.network "private_network", ip: "172.16.16.10#{i}"

      node.vm.provider :virtualbox do |v|
        v.name    = "archvm#{i}"
        v.memory  = 512
        v.cpus    = 1
      end

      node.vm.provider :libvirt do |v|
        v.nested  = true
        v.memory  = 1024
        v.cpus    = 1
      end

    end

  end

end
